#!/bin/sh

# Set these paths appropriately

BIN="/mnt/nfs/scratch1/hschang/language_modeling/NSD_for_sentence_embedding/src/testing/sim/tree_tagger/bin"
CMD="/mnt/nfs/scratch1/hschang/language_modeling/NSD_for_sentence_embedding/src/testing/sim/tree_tagger/cmd"
LIB="/mnt/nfs/scratch1/hschang/language_modeling/NSD_for_sentence_embedding/src/testing/sim/tree_tagger/lib"

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
TAGGER=${BIN}/tree-tagger
ABBR_LIST=${LIB}/romanian-abbreviations
PARFILE=${LIB}/romanian.par

$TOKENIZER -r -a $ABBR_LIST $* |
${CMD}/split-romanian.perl ${LIB}/romanian-tokens |
$TAGGER $OPTIONS $PARFILE
