#!/bin/sh

# Set these paths appropriately

BIN="/mnt/nfs/scratch1/hschang/language_modeling/NSD_for_sentence_embedding/src/testing/sim/tree_tagger/bin"
CMD="/mnt/nfs/scratch1/hschang/language_modeling/NSD_for_sentence_embedding/src/testing/sim/tree_tagger/cmd"
LIB="/mnt/nfs/scratch1/hschang/language_modeling/NSD_for_sentence_embedding/src/testing/sim/tree_tagger/lib"

OPTIONS="-token -lemma -sgml"

TAGGER=${BIN}/tree-tagger
TOKENIZER=${CMD}/tokenize-korean.pl
PARFILE=${LIB}/korean.par

$TOKENIZER $* |
$TAGGER $OPTIONS $PARFILE |
$CMD/add-korean-sentence-markers.pl |
$CMD/reformat-korean-tagger-output.pl
