#!/bin/sh

# Set these paths appropriately

BIN="/mnt/nfs/scratch1/hschang/language_modeling/NSD_for_sentence_embedding/src/testing/sim/tree_tagger/bin"
CMD="/mnt/nfs/scratch1/hschang/language_modeling/NSD_for_sentence_embedding/src/testing/sim/tree_tagger/cmd"
LIB="/mnt/nfs/scratch1/hschang/language_modeling/NSD_for_sentence_embedding/src/testing/sim/tree_tagger/lib"

OPTIONS="-token -lemma -sgml"

TAGGER=${BIN}/tree-tagger
TOKENIZER=${CMD}/utf8-tokenize.perl
ABBR_LIST=${LIB}/dutch-abbreviations
PARFILE=${LIB}/dutch.par

$TOKENIZER -a $ABBR_LIST $* |
$TAGGER $OPTIONS $PARFILE
